version: "3.8"

services:
  spring_boot_app:
    container_name: spring_boot_app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/spring_boot_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - backend_network
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_boot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend_network

volumes:
  pgdata:

networks:
  backend_network:
    driver: bridge
